version: '3'

services:

  simple_qa:
      image: simple_qa:latest
      restart: always
      ports:
          - 5000:5000
      volumes:
          - ../data:/opt/chatbot/data
      working_dir: /opt/chatbot
      environment:
          BOT_INPUT:
          BOT_MODEL:
          BOT_SCORELIMIT: 0.4
